"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var cliente_1 = require("./modelos/cliente");
var endereco_1 = require("./modelos/endereco");
var telefone_1 = require("./modelos/telefone");
var documento_1 = require("./modelos/documento");
var tipoDocumento_1 = require("./enumeracoes/tipoDocumento");
var cliente = new cliente_1.default();
cliente.nome = "Pedro de Alc\u00E2ntara Jo\u00E3o Carlos Leopoldo Salvador";
cliente.nomeSocial = "Dom Pedro II";
cliente.dataCadastro = new Date(1840, 6, 23);
cliente.dataNascimento = new Date(1825, 11, 2);
var endereco = new endereco_1.default();
endereco.rua = "R. do Catete";
endereco.bairro = "Copacabana";
endereco.cidade = "Rio de Janeiro";
endereco.estado = "Rio de Janeiro";
endereco.pais = "Brasil";
endereco.codigoPostal = "22220-000";
var telefone = new telefone_1.default();
telefone.ddd = "21";
telefone.numero = "99999-9999";
var documento = new documento_1.default();
documento.numero = "123.456.789-00";
documento.tipo = tipoDocumento_1.TipoDocumento.CPF;
documento.dataExpedicao = new Date(1840, 6, 23);
cliente.telefone.push(telefone);
cliente.endereco = endereco;
cliente.documentos.push(documento);
var dependente = new cliente_1.default();
dependente.nome = "Isabel Cristina Leopoldina Augusta Micaela";
dependente.nomeSocial = "Princesa Isabel";
dependente.dataCadastro = new Date(1921, 10, 14);
dependente.dataNascimento = new Date(1846, 6, 29);
dependente.endereco = cliente.endereco.clonar();
dependente.titular = cliente;
cliente.dependentes.push(dependente);
console.log(cliente);
console.log(dependente);
